/* =========================================================
   Orbita Akademiya — kurslar katalogi (yagona manba).
   Narxlar shu yerda — server to'lov summasini faqat shu fayldan oladi,
   brauzerdan kelgan summaga ishonilmaydi.
   price: so'mda. 0 = bepul kurs.
   Pullik kurslarda 1-dars (index 0) hamma uchun bepul (sinov darsi).
   ========================================================= */
const CATALOG = [
  { id:'python', icon:'🐍', c:'#6CE4F0', level:1, price:0, hours:4,
    title:'Python asoslari', sub:'Noldan birinchi dasturgacha: o‘zgaruvchi, shart, sikl, funksiya.',
    lessons:['Python nima va birinchi dastur','O‘zgaruvchilar va ma’lumot turlari','Shartlar: if, elif, else','Sikllar: for va while','Ro‘yxatlar va lug‘atlar','Funksiyalar'],
    yt:[
      [['dguiNk8eHPY','Birinchi dasturimiz — Mohirdev'],['djtv5NMIBSY','print() va arifmetik amallar — Mohirdev']],
      [['4-Sj_owtx3Q','O‘zgaruvchilar (Variables) — Mohirdev']],
      [['QH5Q_dyj3dI','if-else shartlari va tarmoqlanish — Mohirdev']],
      [['982dbRh0Efg','for tsikli — Mohirdev'],['Wpp6tXpMGgM','while tsikli — Mohirdev']],
      [['92UuA1jneuQ','Ro‘yxatlar (Lists) — Mohirdev'],['s2SsA2_64o4','Lug‘at (Dictionary) — Mohirdev']],
      [['_aDyBPYAeyU','Funksiya — Mohirdev'],['VqEWbr1erXc','Funksiyadan qiymat qaytarish — Mohirdev']]] },
  { id:'htmlcss', icon:'🌐', c:'#FF7A45', level:1, price:39000, hours:4,
    title:'HTML va CSS: birinchi sayt', sub:'Sahifa tuzilmasi, dizayn, Flexbox va telefonga moslash.',
    lessons:['Veb qanday ishlaydi, HTML skeleti','Matn, havola, rasm va ro‘yxatlar','CSS: rang, shrift, selektorlar','Box model: margin, padding, border','Flexbox bilan joylashtirish','Responsive dizayn va saytni joylash'],
    yt:[
      [['E9OKpacyUSc','WEB qanday ishlaydi — Ulug‘bek Samigjonov'],['_j7yneg6if0','HTML’ga kirish — Ulug‘bek Samigjonov']],
      [['L9GXV5ze6rk','Havolalar (Links) — Ulug‘bek Samigjonov'],['ehmdzmoBvCc','Rasmlar (Images) — Ulug‘bek Samigjonov']],
      [['3iu0XhZpr_U','CSS 1-qism — Ulug‘bek Samigjonov'],['0UsPKt4gU9I','CSS selektorlar — Ulug‘bek Samigjonov']],
      [['WKUqpFVQnj8','Box model: margin, padding, border — Ulug‘bek Samigjonov']],
      [['j06i3epVpsI','Flexbox: asoslar va terminlar — Ulug‘bek Samigjonov']],
      [['Zts7IrRfe-c','Responsive Web Design — Ulug‘bek Samigjonov'],['U_mBrFiClvw','HTML loyiha (Project) — Ulug‘bek Samigjonov']]] },
  { id:'git', icon:'🌿', c:'#7CF0A6', level:1, price:29000, hours:3,
    title:'Git va GitHub', sub:'Kod tarixini saqlash, jamoada ishlash va portfolio.',
    lessons:['Versiya nazorati nima uchun kerak','git init, add, commit','Tarix: log, diff, qaytarish','Branch va merge','GitHub: push, pull, clone','Pull request va portfolio'],
    yt:[
      [['REFazt1lsow','GitHub haqida qisqacha — Alitech'],['GYmLXBlTqfE','Git va GitHub — to‘liq kurs (Azizbek Khabibullaev)']],
      [['9ecBtlfYSpA','git add — Alitech'],['4x1qI8jJ8zY','git commit: xotiraga joylash — Alitech']],
      [['zu7jQ_9NZJY','Fayl o‘zgarishini bekor qilish — Alitech']],
      [['xYn8gDOMuAg','git merge: ikki tarmoqni birlashtirish — Code Leader']],
      [['Yzc9BSC8rwk','Git va GitHub’ni to‘liq o‘rganish (push, pull, clone) — Suxrob Nurali']],
      [['lD3VCVfZjc4','GitHubda Pull Request qilish — Uzbek Student']]] },
  { id:'aiprompt', icon:'✨', c:'#B79CFF', level:1, price:49000, hours:3,
    title:'AI va prompt muhandisligi', sub:'ChatGPT kabi AI bilan to‘g‘ri ishlash, xavfsizlik va amaliy usullar.',
    lessons:['Sun’iy intellekt va LLM nima','Yaxshi prompt formulasi','Misollar bilan o‘rgatish (few-shot)','AI bilan o‘qish va kod yozish','AI xatolari va tekshirish','AI’ni dasturga ulash (API)'],
    yt:[
      [['1hNxd2ldlRY','Sun’iy intellekt va Machine Learning nima? — Mohirdev']],
      [['1bUVKSbqDYA','To‘g‘ri prompt yozish — Dilafruz'],['FTm5MVl09S4','12 ta effektli prompt — Rashidkhon AI']],
      [['1u5qWfD13VQ','ChatGPT’ni PRO darajada o‘rganish — Azizbek Baxodirov']],
      [['eqCHHQoxUeo','AI’dan to‘g‘ri foydalanish — Najot Ta’lim'],['uewtWnntOZM','NotebookLM bilan 10x tez o‘rganish — Najot Ta’lim']],
      [['D6rUKLqRLoI','Sun’iy intellektga qanchalik ishonish mumkin? — Mohirdev']],
      [['_ZvnD73m40o','AI’ni dasturga ulash — API bilan ishlash (inglizcha)']]] },
  { id:'js', icon:'⚡', c:'#FFD66B', level:2, price:59000, hours:5,
    title:'JavaScript asoslari', sub:'Saytni jonlantirish: o‘zgaruvchi, funksiya, DOM va hodisalar.',
    lessons:['JavaScript nima, konsol va birinchi kod','O‘zgaruvchi, tur va operatorlar','Shartlar va sikllar','Funksiyalar va massivlar','DOM: sahifani boshqarish','Hodisalar va mini-loyiha'],
    yt:[
      [['q8yclECd9CY','Kirish — Javascript asoslari (Ulug‘bek Samigjonov)']],
      [['0WT9klSJl38','Qiymatlar va o‘zgaruvchilar — Ulug‘bek Samigjonov']],
      [['MVWjDj_OAEc','if / else — Ulug‘bek Samigjonov']],
      [['uCYtOcs5BSY','Funksiya va uni e’lon qilish — Ulug‘bek Samigjonov']],
      [['ZH_RUUX1fc0','DOM — Ulug‘bek Samigjonov']],
      [['63ljVlWgCCQ','Hodisalar (events) — Ulug‘bek Samigjonov']]] },
  { id:'oop', icon:'🧱', c:'#5CF2B5', level:2, price:69000, hours:4,
    title:'Python: funksiyalar va OOP', sub:'Klass, obyekt, vorislik — katta dasturlarni tartibli yozish.',
    lessons:['Funksiyalar chuqurroq: args, return','Modullar va fayllar bilan ishlash','Klass va obyekt','Metodlar va __init__','Vorislik va polimorfizm','Xatolarni ushlash (try/except)'],
    yt:[
      [['uzNp5XNOZ_I','Moslashuvchan funksiyalar — Mohirdev'],['vNeZD2LTI94','Funksiyaga ro‘yxat uzatish — Mohirdev']],
      [['SEQzCcXY4Pc','Modullar — Mohirdev'],['3JIhjqXNWj0','Fayllar bilan ishlash — Mohirdev']],
      [['1CascMOFoi0','Object Oriented dasturlash nima? — Mohirdev'],['Mi0GzaBguEQ','Klass va obyekt — Mohirdev']],
      [['KOKEsau2uaU','Dunder metodlar 1-qism — Mohirdev'],['ltTOXJJiPRk','Dunder metodlar 2-qism — Mohirdev']],
      [['JnoQ-2SFPnY','Vorislik va polimorfizm — Mohirdev']],
      [['xgXGCaMX_sY','Xatolar bilan ishlash: try-except — Mohirdev'],['Zp8hhWN_qwQ','Eng ko‘p uchraydigan xatolar — Mohirdev']]] },
  { id:'sql', icon:'🗄️', c:'#6CA8FF', level:2, price:69000, hours:4,
    title:'SQL va ma’lumotlar bazasi', sub:'Jadval yaratish, so‘rov yozish, JOIN va hisobotlar.',
    lessons:['Ma’lumotlar bazasi nima','CREATE TABLE va INSERT','SELECT va WHERE','ORDER BY, GROUP BY va agregatlar','JOIN: jadvallarni bog‘lash','UPDATE, DELETE va xavfsizlik'],
    yt:[
      [['G-qW4fzhboI','Ma’lumotlar bazasiga kirish, SQL haqida — SQL darslari']],
      [['W-z8UJSbukI','CREATE DATABASE va CREATE TABLE — SQL darslari']],
      [['_KJzMkffd_k','SELECT va WHERE — SQL darslari']],
      [['rUhRuOWFn4k','Agregat funksiyalar — Bexruz Xolmuminov']],
      [['FX4AFqP9Jow','JOIN: jadvallarni bog‘lash — SQL darslari']],
      [['9HFRpkPh-gA','ALTER TABLE — SQL darslari'],['E-VHjVqUM6c','SQL injection va himoya — Farkhod Dadajanov']]] },
  { id:'tgbot', icon:'🤖', c:'#5CF2FF', level:2, price:79000, hours:4,
    title:'Telegram bot yaratish', sub:'Python va aiogram bilan ishlaydigan bot — noldan serverga qadar.',
    lessons:['Bot qanday ishlaydi, BotFather','Birinchi bot: /start javobi','Tugmalar va menyular','Foydalanuvchi ma’lumotini saqlash','Holatlar (FSM) va anketa','Botni serverga joylash'],
    yt:[
      [['oRSa8NXWMXQ','Kurs bilan tanishuv — Mohirdev'],['NVE9VpjUbJI','botFather — Mohirdev']],
      [['5qUTBMJLGfM','Kerakli dasturlar — Mohirdev'],['FXu9Y0BN1a0','aiogram — Mohirdev']],
      [['kR4c8FSF6LY','wikibot: birinchi ishlaydigan bot — Mohirdev']],
      [['eID-mIzjb-E','API nima? — Mohirdev'],['1WRJQV3-lws','Pythonda API bilan ishlash — Mohirdev']],
      [['s39kn9KFyP0','speakEnglish bot — Mohirdev'],['3Wlck2Su5Rc','imloBot: bot dasturi — Mohirdev']],
      [['b6w9lS-OkPo','Botni serverga yuklash — Mohirdev']]] },
  { id:'pandas', icon:'📊', c:'#FF5D8F', level:3, price:99000, hours:5,
    title:'Pandas bilan ma’lumot tahlili', sub:'CSV o‘qish, tozalash, guruhlash va grafik — real biznes savollari.',
    lessons:['Ma’lumot tahlili va Pandas','DataFrame: o‘qish va ko‘rish','Tanlash va filtrlash','Tozalash: bo‘sh va takroriy qiymatlar','groupby va hisobotlar','Grafik va xulosa yozish'],
    yt:[
      [['camZxi1ttwk','Pandas 1-dars — Azamat (Dasturlash yo‘li)']],
      [['_BwIgvj2xlk','Pandas 2-dars — Azamat'],['RE668-D1qKM','Pandas atributlari — Python darsliklari']],
      [['RelVQxtfvzA','NumPy va Pandas: dataset bilan ishlash — MachineLearning_IT']],
      [['fGwg_idwH6I','Data Cleaning amaliyoti — Azamat']],
      [['vmEHCJofslg','Pandas groupby va hisobotlar (inglizcha)']],
      [['0j_u_seH9BQ','Matplotlib va Seaborn bilan grafiklar — MachineLearning_IT']]] },
  { id:'algo', icon:'🧠', c:'#E0A96D', level:3, price:119000, hours:6,
    title:'Algoritmlar va ma’lumot tuzilmalari', sub:'Murakkablik, qidiruv, saralash va olimpiada/intervyu fikrlashi.',
    lessons:['Algoritm nima, Big-O','Chiziqli va ikkilik qidiruv','Saralash algoritmlari','Stek va navbat','Rekursiya','Hash-jadval va lug‘at'],
    yt:[
      [['B56tkdlfuec','Algoritmlar kursiga kirish — Mohirdev']],
      [['KGWsvmYVBbM','Binary search — Mohirdev']],
      [['ZiLa_O8BQX0','Selection sort — Mohirdev']],
      [['AQ0dZdOMmmU','Stack va rekursiya — Mohirdev']],
      [['x9bCJYRTh3k','Rekursiya — Mohirdev']],
      [['_BkKaTQq2aI','Hash tables — Mohirdev']]] },
  { id:'backend', icon:'🛰️', c:'#FFB547', level:3, price:129000, hours:6,
    title:'Web API va Backend (FastAPI)', sub:'Server, REST API, ma’lumotlar bazasi va xavfsizlik — o‘z API’ingiz.',
    lessons:['Backend va HTTP qanday ishlaydi','FastAPI: birinchi endpoint','Path va query parametrlar','Pydantic bilan ma’lumot tekshirish','Bazaga ulash (CRUD)','Autentifikatsiya va joylash'],
    yt:[
      [['C5nxrRGHqyU','FastAPI kursi #00 — kirish (o‘zbekcha)'],['D4vx51L8Qy4','FastAPI: 0 dan to‘liq backend API — Axmadjon Qaxxorov']],
      [['ZVLMCISDI2Y','FastAPI kursi #01 — birinchi endpoint']],
      [['Zo5_1SwaYAs','FastAPI kursi #02 — parametrlar bilan ishlash']],
      [['It-UsZZiNkE','FastAPI kursi #03 — ma’lumotni tekshirish']],
      [['gBtwxKyFNdc','TODO app: database bilan ishlash — FastAPI kursi']],
      [['cGZZB49uk_Y','Loyihani Render hostingiga deploy qilish — FastAPI kursi']]] },
  { id:'ml', icon:'🚀', c:'#E25CFF', level:3, price:149000, hours:7,
    title:'Machine Learning asoslari', sub:'Model qanday o‘rganadi: regressiya, klassifikatsiya va baholash.',
    lessons:['Machine Learning nima','Ma’lumotni tayyorlash','Chiziqli regressiya','Klassifikatsiya: qaror daraxti','Modelni baholash','Birinchi ML loyiha'],
    yt:[
      [['o8WR4gPw1Kk','Machine Learning darslari: kirish — ML Lab'],['1hNxd2ldlRY','Machine Learning nima? — Mohirdev']],
      [['spKGdArY2P0','Preprocessing va data transformation — Kodnoma']],
      [['5s6HAek4ujE','Chiziqli regressiya (model tasnifi) — ML Lab'],['8-0HMFAry9g','Chiziqli regressiya — to‘liq qo‘llanma (Otabek Yorqinov)']],
      [['-Ivvkq6MkHo','Supervised Learning: klassifikatsiya — ML Lab']],
      [['gSxe9r4Kmu0','Metrics: modelni baholash — Kodnoma'],['wy1lygqBkUA','ML metrics: yakuniy dars — Kodnoma']],
      [['yvfs6FssaX0','Scikit-learn’ga kirish — Kodnoma'],['UR_viMGMA1k','Google Colab’da AI loyihasi — Kodnoma']]] }
];
const LEVELS = { 1:'Boshlang‘ich', 2:'O‘rta', 3:'Chuqur' };
const PASS = 0.7; // yakuniy imtihondan o'tish chegarasi
function byId(id){ return CATALOG.find(c => c.id === id) || null; }
module.exports = { CATALOG, LEVELS, PASS, byId };
